CREATE TABLE db_test.logsss (
    timestamp DateTime64(3),
    level String,
    sys String,
    mrf String,
    user String,
    script_id String,
    script_name String,
    script_key String,
    script_version String,
    script_process String,
    action String,
    action_entity String,
    action_id String,
    action_data String,
    message String,
    script_step_id String,
    script_step_name String,
    current_script_name String,
    current_script_key String,
    current_script_version String,
    block_type String,
    parameters String,
    timezone String,
    communication_id String,
    communication_number String,
    integration_service_id String,
    duration Float32,
    client_mrf String,
    session String,
    script_owner String,
    current_script_owner String,
    script_responsible String,
    current_script_responsible String,
    crm_departament String
) ENGINE = MergeTree()
ORDER BY timezone;

