version: '3'
services:
  clickhouse-server-test:
    image: bitnami/clickhouse:latest
    container_name: clickhouse-server_2
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=pivanet
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.2.3
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=xDbjnEidiZ8ixmKgR-FpfcMqwg13Y-a0E3y3I-0DBAY=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["webserver"]

  airflow-scheduler:
    image: apache/airflow:2.2.3
    restart: always
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=xDbjnEidiZ8ixmKgR-FpfcMqwg13Y-a0E3y3I-0DBAY=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: ["scheduler"]

volumes:
  postgres_db:
